#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOFU_DIR="$REPO_ROOT/opentofu/semaphore-homelab-infra-project"

# Ensure semaphore data directory exists and is writable by the 'semaphore' user/group.
# Uses sudo when needed.
SEMAPHORE_DATA_DIR="/var/lib/semaphore"
if [ ! -d "$SEMAPHORE_DATA_DIR" ]; then
  echo "Creating $SEMAPHORE_DATA_DIR"
  if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then
      sudo mkdir -p "$SEMAPHORE_DATA_DIR"
    else
      mkdir -p "$SEMAPHORE_DATA_DIR"
    fi
  else
    mkdir -p "$SEMAPHORE_DATA_DIR"
  fi
fi

# Set ownership to semaphore:semaphore and grant rwx to owner/group
if id -u semaphore >/dev/null 2>&1; then
  echo "Setting ownership and permissions on $SEMAPHORE_DATA_DIR"
  if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then
      sudo chown -R semaphore:semaphore "$SEMAPHORE_DATA_DIR"
      sudo chmod -R 770 "$SEMAPHORE_DATA_DIR"
    else
      chown -R semaphore:semaphore "$SEMAPHORE_DATA_DIR" 2>/dev/null || true
      chmod -R 770 "$SEMAPHORE_DATA_DIR" 2>/dev/null || true
    fi
  else
    chown -R semaphore:semaphore "$SEMAPHORE_DATA_DIR"
    chmod -R 770 "$SEMAPHORE_DATA_DIR"
  fi
else
  echo "Warning: user 'semaphore' not found; created directory but did not change ownership."
fi

# Persist environment for the semaphore service/user
# Prefer storing secrets in a file owned with restricted perms and referenced by systemd.
# Gather values from current environment (allow existing exports or fallbacks)
export SEMAPHOREUI_API_BASE_URL="http://127.0.0.1:3000/api"
export SEMAPHORE_FORWARDED_ENV_VARS='["SEMAPHOREUI_BASE_URL","SEMAPHOREUI_API_TOKEN"]'

ENV_FILE_PATH="$SEMAPHORE_DATA_DIR/semaphore.env"

echo "Writing persistent semaphore env to $ENV_FILE_PATH"
tmpfile="${ENV_FILE_PATH}.$$.tmp"
{
  printf "# Generated by bootstrap/semaphore-opentofu.sh\n"
  printf "SEMAPHOREUI_API_BASE_URL=%s\n" "$SEMAPHOREUI_API_BASE_URL"
  printf "SEMAPHOREUI_API_TOKEN=%s\n" "$SEMAPHOREUI_API_TOKEN"
  printf "SEMAPHORE_FORWARDED_ENV_VARS=%s\n" "$SEMAPHORE_FORWARDED_ENV_VARS"
} >"$tmpfile"

# Secure the file and move into place
if id -u semaphore >/dev/null 2>&1; then
  if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
    sudo mv "$tmpfile" "$ENV_FILE_PATH"
    sudo chown root:semaphore "$ENV_FILE_PATH"
    sudo chmod 0640 "$ENV_FILE_PATH"
  else
    mv "$tmpfile" "$ENV_FILE_PATH"
    chown root:semaphore "$ENV_FILE_PATH" 2>/dev/null || true
    chmod 0640 "$ENV_FILE_PATH" 2>/dev/null || true
  fi
else
  # No semaphore user; fall back to root-owned file so systemd can still read it
  if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
    sudo mv "$tmpfile" "$ENV_FILE_PATH"
    sudo chown root:root "$ENV_FILE_PATH"
    sudo chmod 0600 "$ENV_FILE_PATH"
  else
    mv "$tmpfile" "$ENV_FILE_PATH"
    chmod 0600 "$ENV_FILE_PATH" 2>/dev/null || true
  fi
fi

# Create systemd drop-in to load EnvironmentFile if systemd is present
if command -v systemctl >/dev/null 2>&1; then
  dropin_dir="/etc/systemd/system/semaphore.service.d"
  dropin_file="$dropin_dir/10-environment.conf"
  echo "Installing systemd drop-in $dropin_file"
  if [ ! -d "$dropin_dir" ]; then
    if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
      sudo mkdir -p "$dropin_dir"
    else
      mkdir -p "$dropin_dir"
    fi
  fi

  conf_tmp="${dropin_file}.$$.tmp"
  {
    printf "[Service]\n"
    printf "EnvironmentFile=%s\n" "$ENV_FILE_PATH"
  } >"$conf_tmp"

  if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
    sudo mv "$conf_tmp" "$dropin_file"
    sudo chmod 0644 "$dropin_file"
  else
    mv "$conf_tmp" "$dropin_file"
    chmod 0644 "$dropin_file" 2>/dev/null || true
  fi

  echo "Reloading systemd and restarting semaphore.service (if present)"
  if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
    sudo systemctl daemon-reload || true
    sudo systemctl restart semaphore.service || true
  else
    systemctl daemon-reload || true
    systemctl restart semaphore.service || true
  fi
else
  echo "systemd not detected; created $ENV_FILE_PATH for manual consumption by Semaphore runner."
fi

if ! command -v tofu >/dev/null 2>&1; then
  echo "ERROR: OpenTofu (tofu) is not installed or not in PATH." >&2
  exit 1
fi

pushd "$TOFU_DIR" >/dev/null
tofu init -input=false
tofu apply -auto-approve

echo ""
echo "Outputs (store these securely):"
echo "github_public_key:"
tofu output -raw github_public_key
popd >/dev/null
