---

- name: Create new LXC container for docker application
  ansible.builtin.import_playbook:
    file: ../proxmox/create-lxc.yml

- name: Apply Docker Role to LXC Container
  hosts: provisioning
  become: true
  gather_facts: true
  pre_tasks:
    - name: Load user vars
      ansible.builtin.import_tasks: ../../tasks/load-user-vars.yml
  roles:
    - docker
