homelabinfra_defaults:
  networks: {}
  ansible:
    ssh_user: root
  proxmox:
    api_port: 8006
    api_user: root@pam
    lxc:
      disk_volume:
        storage: local
        size: 8
      password: changeme
      cores: 1
      description: LXC Container created by Ansible
      features:
        nesting: true
      memory: 512
      onboot: true
      tags:
        - homelab-infra
    vm: #TODO: EVerything about VM stuff
      agent: 1
      onboot: true
      autostart: true
      description: VM created by Ansible
      tags:
        - homelab-infra
  docker_hosts:
    docker_default_host:
      type: vm

