---
# https://docs.ansible.com/projects/ansible/latest/collections/community/docker/docker_network_info_module.html

- name: "network-info.yml"
  gather_facts: true
  hosts: docker
  vars:

  tasks:
    - name: "Get Docker Network Info"
      community.docker.docker_network_info:
        debug:
        name:
        timeout:
        tls:
        tls_hostname:
        use_ssh_client:
