---
# https://docs.ansible.com/projects/ansible/latest/collections/community/docker/docker_prune_module.html

- name: "prune.yml"
  gather_facts: true
  hosts: docker
  vars:

  tasks:
    - name: "Prune Docker Resources"
      community.docker.docker_prune:
        builder_cache:
        builder_cache_all:
        builder_cache_filters:
        builder_cache_keep_storage:
        containers:
        containers_filters:
        debug:
        images:
        images_filters:
        networks:
        networks_filters:
        timeout:
        tls:
        tls_hostname:
        use_ssh_client:
        volumes:
        volumes_filters:
