---
# https://docs.ansible.com/projects/ansible/latest/collections/community/proxmox/proxmox_module.html

- name: Create LXC container on proxmox host
  hosts: proxmox_host
  become: false
  gather_facts: true

  vars_files:
    - ../../vars/homelabinfra.yml

  tasks:
    - name: Set instance data for LXC container
      ansible.builtin.set_fact:
        homelabinfra:
          config: >-
            {{
              dict(
                ansible = homelabinfra_defaults.ansible | combine(config.ansible | default({}), recursive=True),
                proxmox = homelabinfra_defaults.proxmox | combine(config.proxmox | default({}), recursive=True),
                lxc = homelabinfra_defaults.lxc | combine(config.lxc | default({}), recursive=True),
              )
            }}

    - name: Proxmox Create LXC Container
      ansible.builtin.include_tasks:
        file: ../../tasks/proxmox/lxc-create.yml