---
# https://docs.ansible.com/projects/ansible/latest/collections/community/proxmox/proxmox_module.html

- name: Create LXC container on proxmox host
  hosts: proxmox_nodes
  become: false
  gather_facts: true

  pre_tasks:
    - name: Load user vars
      ansible.builtin.import_tasks: ../../tasks/load-user-vars.yml

  tasks:
# TODO: Create task for deterministic configuration of LXC configuration
    - name: Proxmox Create LXC Container
      ansible.builtin.include_tasks:
        file: ../../tasks/proxmox/lxc-create.yml

    - name: Add LXC to inventory
      ansible.builtin.add_host:
        name: "{{ homelabinfra_instance.lxc.hostname }}"
        groups: provisioning
        ansible_host: "{{ homelabinfra_instance.lxc.ip_address }}"
        ansible_user: "root"
        ansible_ssh_private_key_file: "~/.ssh/id_rsa"

# TODO: Create a task to wait/test for the LXC to be fully up and running before proceeding
# TODO: Create a task to setup some basics like SSH keys, updating commands, report commands, etc, etc.  
