---
# https://docs.ansible.com/projects/ansible/latest/collections/community/proxmox/proxmox_nic_module.html

- name: "nic.yml"
  gather_facts: true
  hosts: proxmox
  vars:

  tasks:
    - name: "Manage Proxmox VM NIC"
      community.general.proxmox_nic:
        api_host:
        api_password:
        api_port: 8006
        api_token_id:
        api_token_secret:
        api_user:
        bridge:
        firewall:
        interface:
        link_down:
        mac:
        model:
        mtu:
        name:
        queues:
        rate:
        state:
        tag:
        trunks:
        validate_certs:
        vmid:
