---
# https://docs.ansible.com/projects/ansible/latest/collections/community/proxmox/proxmox_snap_info_module.html

- name: "snap-info.yml"
  gather_facts: true
  hosts: proxmox
  vars:

  tasks:
    - name: "Get Proxmox Snapshot Info"
      community.general.proxmox_snap_info:
        api_host:
        api_password:
        api_port: 8006
        api_token_id:
        api_token_secret:
        api_user:
        hostname:
        snapname:
        validate_certs:
        vmid:
