---
# https://docs.ansible.com/projects/ansible/latest/collections/community/proxmox/proxmox_vm_info_module.html

- name: "vm-info.yml"
  gather_facts: true
  hosts: proxmox
  vars:

  tasks:
    - name: "Get Proxmox VM Info"
      community.general.proxmox_vm_info:
        api_host:
        api_password:
        api_port: 8006
        api_token_id:
        api_token_secret:
        api_user:
        config:
        name:
        network:
        node:
        type:
        validate_certs:
        vmid:
