---

- name: Assert homelabinfra instance data is provided
  ansible.builtin.assert:
    that:
      - homelabinfra_config is defined
      - homelabinfra_config.ansible.ssh_public_key is defined
      - homelabinfra_config.proxmox.api_host is defined
      - homelabinfra_config.proxmox.api_token_id is defined
      - homelabinfra_config.proxmox.api_token_secret is defined
      - homelabinfra_config.proxmox.node is defined
      - homelabinfra_config.proxmox.lxc.vmid is defined
      - homelabinfra_config.proxmox.lxc.hostname is defined
      - homelabinfra_config.proxmox.lxc.ostemplate is defined
      - homelabinfra_config.proxmox.lxc.ip_address is defined
    fail_msg: "Required homelabinfra_config inputs: ansible[ssh_public_key], proxmox[api_host,api_token_id,api_token_secret,node,lxc[vmid,hostname,ostemplate,ip_address]]"

- name: Build facts for usage in proxmox lxc creation
  ansible.builtin.set_fact:
    homelabinfra_instance:
      lxc: >-
        {{ dict(
          state = 'present',
          api_host = homelabinfra_config.proxmox.api_host,
          api_port = homelabinfra_config.proxmox.api_port,
          api_token_id = homelabinfra_config.proxmox.api_token_id,
          api_token_secret = homelabinfra_config.proxmox.api_token_secret,
          node = homelabinfra_config.proxmox.node,
          pubkey = homelabinfra_config.ansible.ssh_public_key
        ) | combine(homelabinfra_config.proxmox.lxc, recursive=True) }}

- name: Create LXC container
  community.proxmox.proxmox: "{{ homelabinfra_instance.lxc }}"
  register: create_lxc_result

- name: Stamp LXC.conf with instance data
# TODO: We need to properly insert into the commented area to show up as notes (and make it pretty!)
# TODO: Find a better way to store LXC config data than overwriting the proxmox generated config file
  ansible.builtin.command:
    cmd: >
      cat > /etc/pve/lxc/{{ homelabinfra_instance.lxc.vmid }}.conf << EOF
      {{ homelabinfra_instance.lxc | to_nice_json }}
      EOF
  #delegate_to: "{{ homelabinfra_instance.lxc.ip_address }}"
  #become: true
  #become_user: root
